version: '3'

services:
    php:
        build:
            context: .docker
            dockerfile: Dockerfile
        image: todo
        container_name: 'todo_php'
        volumes:
            - './:/app:delegated'
            - '.docker/php.ini:/etc/php/8.0/fpm/conf.d/php.ini:cached'
        depends_on:
            - mariadb
            - redis

    nginx:
        image: nginx
        container_name: 'todo_nginx'
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_SECURE_PORT:-443}:443'
            - '${VITE_PORT:-5175}:${VITE_PORT:-5175}'
        volumes:
            - './:/app:delegated'
            - '.docker/nginx.conf:/etc/nginx/conf.d/default.conf:cached'
            - '.docker/certs:/etc/nginx/certs:cached'
        depends_on:
            - php

    mariadb:
        image: mariadb
        container_name: 'todo_mariadb'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql:cached'

    redis:
        image: redis
        container_name: 'todo_redis'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data:cached'
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    mailhog:
        image: mailhog/mailhog
        container_name: 'todo_mailhog'
        ports:
            - '${MAIL_PORT:-1025}:1025'
            - '8025:8025'

volumes:
    mariadb:
        driver: local
    redis:
        driver: local
